#!/bin/sh

set -ue

GIT=$(which git)

###############################################################
# Check deps

[[ -z $GIT ]] && echo "You have to install git plz" && exit 1

###############################################################
# Local functions

anim() {
  i=0
  sp='/-\|'
  n=${#sp}
  printf ' '
  while sleep 0.1; do
    printf "%s\b" "${sp:i++%n:1}"
  done
}

# Download with git ( arg1 = url | arg2 = path )
dl() {
  local pid
  echo -n "dl $1..."
  anim &
  pid=$!
  $($GIT clone $1 $2 2>/dev/null || exit 1)
  echo "[ok]"
  kill $pid # kill anim()
}

# Check if file exist else download ( arg1 = url | arg2 = path )
chk() {
  if [[ -d $2 ]] ; then
    echo "$2 is found"
  else
    dl $1 $2
  fi
}

forZsh() {
  OH_MY_ZSH=~/.oh-my-zsh
  SPACESHIP=$OH_MY_ZSH/themes/spaceship-prompt
  [ -s $OH_MY_ZSH/themes/spaceship.zsh-theme ] && unlink $OH_MY_ZSH/themes/spaceship.zsh-theme
  [ -d $SPACESHIP ] && rm -rf $SPACESHIP
  [ -d $OH_MY_ZSH ] && {
    read -p "Clearing oh-my-zsh for updates? [y/n] "
    if [[ $REPLY =~ ^y|^Y ]] ; then
      rm -rf $OH_MY_ZSH
    else
      echo "Ok, we keep your directory..."
    fi
  }
  chk https://github.com/robbyrussell/oh-my-zsh.git $OH_MY_ZSH
  chk https://github.com/denysdovhan/spaceship-prompt.git $SPACESHIP
  # create symbolic link
  ln -s  $SPACESHIP/spaceship.zsh-theme $OH_MY_ZSH/themes/spaceship.zsh-theme
}

vimcolors() {
  vim_dir=$HOME/.vim/pack/my-plugins/start

  [ -d $vim_dir ] || mkdir -p $vim_dir
  chk https://github.com/kaicataldo/material.vim $vim_dir/material.vim
  chk https://github.com/szorfein/fantasy.vim $vim_dir/fantasy.vim
  chk https://github.com/szorfein/darkest-space $vim_dir/darkest-space
  chk https://github.com/szorfein/fromthehell.vim $vim_dir/fromthehell.vim
  chk https://github.com/szorfein/lightline.vim $vim_dir/lightline.vim
  chk https://github.com/edkolev/tmuxline.vim $vim_dir/tmuxline.vim
  chk https://github.com/sainnhe/gruvbox-material $vim_dir/gruvbox-material
  chk https://github.com/szorfein/sci.vim $vim_dir/sci
}

get_image() {
  img_name="$1"
  url="$2"
  wget -O /tmp/image "https://api.pcloud.com/getpubthumb?code=${url#*=}&linkpassword=undefined&size=2048x2048&crop=0&type=auto"
  if file /tmp/image | grep -iE jpeg\|jpg >/dev/null ; then
    echo "copying $DEST/$1.jpg..."
    mv /tmp/image $DEST/$1.jpg
  elif file /tmp/image | grep -i png >/dev/null ; then
    echo "copying $DEST/$1.png..."
    mv /tmp/image $DEST/$1.png
  else
    echo "extension for $1 is no found :("
    exit 1
  fi
  img_name= url=
}

download_images() {
  DEST=~/images
  [ -d ~/images ] || mkdir ~/images
  filename=
  link=
  while read line; do
    filename=$(echo ${line%-*} | tr -d " ")
    link=$(echo ${line#*-} | tr -d " ")
    if [ -f "${DEST}/${filename}.png" ] ; then
      echo "file: $filename.png exist"
    elif [ -f "${DEST}/${filename}.jpg" ] ; then
      echo "file: $filename.jpg exist"
    else
      echo "file: $filename no exist, download..."
      get_image $filename $link
    fi
  done < hidden-stuff/wallpapers-list.txt
  filename= link= DEST=
}

banner() {
  printf "%s\n" \
    '
      ▓█████▄  ▒█████  ▄▄▄█████▓  █████▒██▓ ██▓    ▓█████   ██████
      ▒██▀ ██▌▒██▒  ██▒▓  ██▒ ▓▒▓██   ▒▓██▒▓██▒    ▓█   ▀ ▒██    ▒
      ░██   █▌▒██░  ██▒▒ ▓██░ ▒░▒████ ░▒██▒▒██░    ▒███   ░ ▓██▄
      ░▓█▄   ▌▒██   ██░░ ▓██▓ ░ ░▓█▒  ░░██░▒██░    ▒▓█  ▄   ▒   ██▒
      ░▒████▓ ░ ████▓▒░  ▒██▒ ░ ░▒█░   ░██░░██████▒░▒████▒▒██████▒▒
      ▒▒▓  ▒ ░ ▒░▒░▒░   ▒ ░░    ▒ ░   ░▓  ░ ▒░▓  ░░░ ▒░ ░▒ ▒▓▒ ▒ ░
      '
    }

  usage() {
    banner
    printf "%s\n" \
      "-z, --zsh    Download and install dependencies of zsh"

    printf "%s\n" \
      "-v, --vim    Download and install vim colorscheme for vim"

    printf "%s\n" \
      "-h, --help   Display this really usefull message"
    }

###############################################################
# Command line options

if [ "$#" -eq 0 ]; then
  printf "%s\\n" "$prog_name: Argument required"
  printf "%s\\n" "Try '$prog_name --help' for more information."
  exit 1
fi

while [ "$#" -gt 0 ] ; do
  case "$1" in
    -z | --zsh)
      banner
      forZsh
      shift
      ;;
    -v | --vim)
      banner
      vimcolors
      shift
      ;;
    -i | --images)
      banner
      download_images
      shift
      ;;
    -h | --help)
      usage
      shift
      ;;
    *)
      usage
      printf "\\n%s\\n" "$prog_name: Invalid option '$1'"
      exit 1
      ;;
  esac
done
